<?php

require_once 'File/Iterator/Autoload.php'; // (already required by CodeCoverage >= 2.0.15)
// require_once 'Text/Template/Autoload.php'; (already required by phpunit-mock-object >= 2.3 and CodeCoverage >= 2.0.15)
require_once 'PHP/CodeCoverage/Autoload.php';
require_once 'PHP/Timer/Autoload.php';
require_once 'PHPUnit/Framework/MockObject/Autoload.php';
require_once 'Prophecy/autoload.php';
require_once 'Symfony/Component/Yaml/autoload.php';
require_once 'SebastianBergmann/Comparator/autoload.php';
// require_once 'SebastianBergmann/Diff/autoload.php'; (already required by Comparator >= 1.1)
require_once 'SebastianBergmann/Environment/autoload.php'; // (already required by CodeCoverage >= 2.0.15)
// require_once 'SebastianBergmann/Exporter/autoload.php'; (already required by Comparator >= 1.1)
require_once 'SebastianBergmann/GlobalState/autoload.php';
require_once 'SebastianBergmann/ResourceOperations/autoload.php';
require_once 'SebastianBergmann/Version/autoload.php'; // (already required by CodeCoverage >= 2.0.15)
require_once 'DeepCopy/autoload.php';

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                ___CLASSLIST___
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require ___BASEDIR___$classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd

if (stream_resolve_include_path('PHP/Invoker/Autoload.php')) {
    require_once 'PHP/Invoker/Autoload.php';
}

if (stream_resolve_include_path('PHPUnit/Extensions/Database/Autoload.php')) {
    require_once 'PHPUnit/Extensions/Database/Autoload.php';
}
